import { Sarabun } from "next/font/google";
import "./globals.css"; 
const sarabun = Sarabun({
  weight: ['400', '700'], // You can specify the weights you want to include
  subsets: ['latin'], // You can specify the subsets you want to include
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sarabun.className}>
        {children}
      </body>
    </html>
  );
}
